SecRuleEngine On
SecRequestBodyAccess On
SecRequestBodyLimit 13107200
SecRequestBodyNoFilesLimit 1048576
SecRequestBodyLimitAction Reject
SecResponseBodyAccess Off

SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:403|429)$"
SecAuditLogParts AZ
SecAuditLogType Serial
SecAuditLog /tmp/modsecurity/modsec_audit.log

SecDataDir /tmp/modsecurity

Include /etc/nginx/modsecurity/custom-rules.conf
